aws_region = "ap-south-1"
ami_id = "ami-02521d90e7410d9f0"   # Ubuntu ami
instance_type = "t2.micro"
instance_user = "ubuntu"
java_version = 21 
shutdown_threshold = 20
repo_url = "https://github.com/techeazy-consulting/techeazy-devops"
bucket_name = "dev-config-bucket"
alert_email = "work.udayrana@gmail.com"