aws_region = "ap-south-1"
ami_id = "ami-02521d90e7410d9f0"   # Ubuntu ami
instance_type = "t2.small"
instance_user = "ubuntu"
java_version = 21 
shutdown_threshold = 60
repo_url = "https://github.com/techeazy-consulting/techeazy-devops"
bucket_name = "prod-config-bucket" 
alert_email = "work.udayrana@gmail.com" 